ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 16:02:14,011
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 21:24:00,057
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:24:39,877
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:24:57,160
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:04,472
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:21,655
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:34,301
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:49,427
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:33:49,773
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:34:10,527
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:35:07,282
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:35:22,034
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:03,327
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:14,001
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:26,885
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:37,787
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:38:24,014
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 261, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 21:39:32,643
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 261, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 21:44:56,154
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:47:34,464
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:48:29,529
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:48:34,955
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:50:00,302
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-08 11:40:32,067
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:40:33,890
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:40:38,958
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:40:41,006
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:45:55,166
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:46:06,184
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:46:10,886
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 12:30:51,863
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 12:34:47,989
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 274, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 12:36:12,342
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 274, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 13:56:27,778
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 10:39:01,502
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 579, in short_gas
    house(11,18,'l',hnum)
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 531, in house
    group('house_l,x')
TypeError: group() missing 1 required positional argument: 'figure'
2021-12-10 10:42:15,554
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 569, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-10 11:02:26,721
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 67, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-10 11:02:26,722
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 283, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-10 11:02:54,782
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 67, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-10 11:02:54,783
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 283, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-10 11:59:01,120
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:02,131
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:02,822
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,029
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,193
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,342
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,503
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,648
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,839
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 08:47:52,450
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 10:36:45,396
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 10:41:19,954
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 313, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-13 11:32:50,213
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 12:28:38,889
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 603, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-13 12:32:33,356
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 603, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-13 13:31:01,118
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 13:50:17,702
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 14:19:53,330
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 305, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 14:19:54,747
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 305, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 14:19:55,612
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 305, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-14 22:48:08,623
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 83, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-14 22:48:08,654
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 330, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-15 08:54:41,974
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-15 09:17:34,997
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 627, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-15 13:17:13,572
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 670, in long_gas
    hlabel('NRE',27,7)
TypeError: hlabel() missing 1 required positional argument: 'size'
2021-12-15 14:29:15,970
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 634, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-15 14:29:18,196
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-15 15:19:08,677
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 345, in ped
    graph,(x-0.4,y-0.4), (x+0.4,y+0.4), line_color='black',fill_color='white',line_width=1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 15:19:08,678
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 261, in pole
    TK.addtag_withtag('pole',p)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel.!frame.!frame.!frame2.!canvas addtag pole withtag tagOrId"
2021-12-15 15:19:08,681
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 337, in item_stamp
    sg.Graph.draw_image(graph,location=(x-0.75,y-0.75),data=convert_to_bytes('Drilling.bmp'))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 15:19:08,681
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 281, in transformer
    txr = graph.draw_rectangle((x - 0.5, y - 0.5), (x + 0.5, y + 0.5), line_color="black")
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 15:19:08,682
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 337, in item_stamp
    sg.Graph.draw_image(graph,location=(x-0.75,y-0.75),data=convert_to_bytes('Drilling.bmp'))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 22:24:39,616
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1209, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-16 09:03:10,168
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-16 09:03:33,343
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-16 21:24:41,611
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 315, in hlabelm
    v2 = graph.draw_text(vlbl, (x, y), font="Arial 3 normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-16 21:32:49,528
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 80, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-16 21:32:49,549
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 315, in hlabelm
    )
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-16 22:23:24,818
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 344, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-17 09:21:06,640
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 338, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-17 12:26:46,349
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 361, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-20 12:55:56,926
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:57,205
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:57,475
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:58,591
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:59,556
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 13:06:31,715
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 714, in read_from_template
    draw_street(flist[1], landbase)
IndexError: list index out of range
2021-12-21 09:02:44,597
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-21 09:02:44,629
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 348, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-21 09:21:57,195
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:21:58,373
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:21:59,836
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:22:02,494
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:22:04,988
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:24:48,573
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 357, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:26:57,471
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1330, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 09:27:18,828
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 10:39:42,549
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 720, in read_from_template
    edge_type = lb_strlist[1].strip()
IndexError: list index out of range
2021-12-21 10:39:47,548
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 10:39:56,726
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 10:40:00,717
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 720, in read_from_template
    edge_type = lb_strlist[1].strip()
IndexError: list index out of range
2021-12-21 16:33:11,604
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:14,385
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:14,656
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:14,832
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:19,949
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,113
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,322
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,483
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,877
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:56:37,550
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in ped
    TK.add_tag_with_tag('ped',pedsq)
AttributeError: 'Canvas' object has no attribute 'add_tag_with_tag'
2021-12-21 16:56:41,778
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in ped
    TK.add_tag_with_tag('ped',pedsq)
AttributeError: 'Canvas' object has no attribute 'add_tag_with_tag'
2021-12-21 16:58:31,844
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in ped
    TK.add_tag_withtag('ped',pedsq)
AttributeError: 'Canvas' object has no attribute 'add_tag_withtag'
2021-12-22 21:56:04,395
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1442, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-22 22:13:26,434
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-22 22:13:26,435
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 389, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-22 23:08:04,390
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-22 23:08:06,272
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
